# I decided to take a stab at the Badge problem from the UC Irvine Repository.
I found it an interesting problem to tackle just because we have to be able to determine labels based on the name.

# I left all my comments in there and it's very cleaned up for a reason. I wanted the reader to follow my thought process as I dealt with this problem.

In [3]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
import pandas as pd

In [5]:
import string

In [6]:
name = pd.read_csv('namelabel.csv', header=None)

In [5]:
name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 1 columns):
0    294 non-null object
dtypes: object(1)
memory usage: 2.4+ KB


In [6]:
name.describe()

0
count                  294
unique                 294
top     - Steven W. Norton
freq                     1

In [7]:
name.head()

0
0        + Naoki Abe
1  - Myriam Abramson
2     + David W. Aha
3     + Kamal M. Ali
4    - Eric Allender

In [8]:
name.columns = name.columns.astype(str)

In [9]:
name

0
0                + Naoki Abe
1          - Myriam Abramson
2             + David W. Aha
3             + Kamal M. Ali
4            - Eric Allender
5             + Dana Angluin
6           - Chidanand Apte
7             + Minoru Asada
8               + Lars Asker
9              + Javed Aslam
10   + Haralabos Athanassiou
11        + Jose L. Balcazar
12       + Timothy P. Barber
13       + Michael W. Barley
14       - Cristina Baroglio
15          + Peter Bartlett
16               - Eric Baum
17           + Welton Becket
18          - Shai Ben-David
19             + George Berg
20            + Neil Berkman
21         + Malini Bhandaru
22               + Bir Bhanu
23         + Reinhard Blasig
24              - Avrim Blum
25           - Anselm Blumer
26            + Justin Boyan
27        + Carla E. Brodley
28           + Nader Bshouty
29            - Wray Buntine
..                       ...
264          - Frank Stephan
265      + Mandayam T. Suraj
266      + Richard S. Sutton
267             + Joe Suzuki
268       - Prasad Tadepalli
269         + Hiroshi Tanaka
270   - Irina Tchoumatchenko
271           - Brian Tester
272           - Chen K. Tham
273           + Tatsuo Unemi
274          - Lyle H. Ungar
275            + Paul Utgoff
276      + Karsten Verbeurgt
277           + Paul Vitanyi
278            + Xuemei Wang
279        + Manfred Warmuth
280             + Gary Weiss
281           - Sholom Weiss
282        - Thomas Wengerek
283   - Bradley L. Whitehall
284           - Alma Whitten
285      + Robert Williamson
286            + Janusz Wnek
287        + Kenji Yamanishi
288      + Takefumi Yamazaki
289            + Holly Yanco
290          + John M. Zelle
291        - Thomas Zeugmann
292     + Jean-Daniel Zucker
293          + Darko Zupanic

[294 rows x 1 columns]

In [18]:
name.columns = ['names']

In [19]:
name.head(2)

names
0        + Naoki Abe
1  - Myriam Abramson

In [10]:
def firstname(allname):
    firstname = allname.split()[1]
    return firstname

def midname(allname):
    if allname.split()[2][1] ==  '.':
        middlename = allname.split()[2]
        return middlename
    
def lastname(allname):
    if allname.split()[2][1] ==  '.':
        lastname = allname.split()[3]    
    else:
        lastname = allname.split()[2]
    return lastname

def label(allname):
    label = allname.split()[0]
    return label

In [20]:
lastname('+ Bradley L. Whitehall')

'Whitehall'

In [21]:
name['first name'] = name['names'].apply(lambda x: firstname(x))

In [22]:
name['middle name'] = name['names'].apply(lambda x: midname(x))

In [23]:
name['last name'] = name['names'].apply(lambda x: lastname(x))

In [24]:
name['label'] = name['names'].apply(lambda x: label(x))

In [26]:
name.head()

names first name middle name last name label
0        + Naoki Abe      Naoki        None       Abe     +
1  - Myriam Abramson     Myriam        None  Abramson     -
2     + David W. Aha      David          W.       Aha     +
3     + Kamal M. Ali      Kamal          M.       Ali     +
4    - Eric Allender       Eric        None  Allender     -

In [28]:
name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 5 columns):
names          294 non-null object
first name     294 non-null object
middle name    61 non-null object
last name      294 non-null object
label          294 non-null object
dtypes: object(5)
memory usage: 11.6+ KB


In [37]:
def remove_none(name):
    
    if name is None:
        return ''
    else:
        return name

In [38]:
name['middle name'] = name['middle name'].apply(remove_none)

In [40]:
name.head()

names first name middle name last name label
0        + Naoki Abe      Naoki                   Abe     +
1  - Myriam Abramson     Myriam              Abramson     -
2     + David W. Aha      David          W.       Aha     +
3     + Kamal M. Ali      Kamal          M.       Ali     +
4    - Eric Allender       Eric              Allender     -

In [41]:
name['length of first'] = name['first name'].apply(len)

name['length of last'] = name['last name'].apply(len)

In [45]:
names = name

names.head()

names first name middle name last name label  length of first  \
0        + Naoki Abe      Naoki                   Abe     +                5   
1  - Myriam Abramson     Myriam              Abramson     -                6   
2     + David W. Aha      David          W.       Aha     +                5   
3     + Kamal M. Ali      Kamal          M.       Ali     +                5   
4    - Eric Allender       Eric              Allender     -                4   

   length of last  
0               3  
1               8  
2               3  
3               3  
4               8

In [46]:
def countVowels(name):
    namevowels = []
    vowels = ['A','a','E','e','I','i','O','o','U','u']
    for letter in name:
        if letter in vowels:
            namevowels.append(letter)
    return len(namevowels)

In [110]:
countVowels('Michel')

2

In [47]:
def countCons(name):
    namecons = []
    vowels = ['A','a','E','e','I','i','O','o','U','u']
    for letter in name:
        if letter not in vowels:
            namecons.append(letter)
    return len(namecons)

In [109]:
vowels = ['A','a','E','e','I','i','O','o','U','u']

In [122]:
countCons('Michael' + 'Acheampong')

10

In [48]:
names.head(2)

names first name middle name last name label  length of first  \
0        + Naoki Abe      Naoki                   Abe     +                5   
1  - Myriam Abramson     Myriam              Abramson     -                6   

   length of last  
0               3  
1               8

In [49]:
names['firstvowels'] = names['first name'].apply(countVowels)

In [50]:
names['firstCons'] = names['first name'].apply(countCons)

In [51]:
names['lastvowels'] = names['last name'].apply(countVowels)

In [52]:
names['lastCons'] = names['last name'].apply(countCons)

In [58]:
names.head(2)

first name middle name last name label  length of first  length of last  \
0      Naoki                   Abe     +                5               3   
1     Myriam              Abramson     -                6               8   

   firstvowels  firstCons  lastvowels  lastCons  
0            3          2           2         1  
1            2          4           3         5

In [59]:
def middlenamedummy(name):
    
    if name == '':
        return 0
    else:
        return 1

In [61]:
names['middledummy'] = names['middle name'].apply(middlenamedummy)

# is there a middle name?

In [62]:
names['totalVowels'] = (names['first name'] + names['middle name'] + names['last name']).apply(countVowels)

# count the number of vowels in the name

In [63]:
names['totalCons'] = (names['first name'] + names['middle name'] + names['last name']).apply(countCons)

# count the number of consonants in the name

In [65]:
names['VtFratio'] = names['totalVowels']/(names['totalVowels']+names['totalCons']) # ratio of number of vowels to total length

names['CtFratio'] = names['totalCons']/(names['totalVowels']+names['totalCons']) # ratio of number of consonants to total length

names['VtCratio'] = names['totalVowels']/names['totalCons'] # ratio of number of vowels to number of consonants

In [95]:
names['FtVratio'] = round((names['totalVowels']+names['totalCons'])/names['totalVowels'],0) # ratio of total length to number of vowels

names['FtCratio'] = round((names['totalVowels']+names['totalCons'])/names['totalCons'],0) # ratio of total length to number of consonants

names['CtVratio'] = round(names['totalCons']/names['totalVowels'],0) # ratio of consonants to vowels

In [103]:
# DUMMIES BASED ON EVEN

# Is the total length an even number?
names['tot_lengthdummy'] = (names['totalVowels']+names['totalCons']).apply(lambda x: 1 if x%2 == 0 else 0)

# Is the length of first name an even number?
names['LoFdummy'] = names['length of first'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the length of last name an even number?
names['LoLdummy'] = names['length of last'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the number of vowels in first name even?
names['FVdummy'] = names['firstvowels'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the number of cons in first name even?
names['FCdummy'] = names['firstCons'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the number of vowels in last name even?
names['LVdummy'] = names['lastvowels'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the number of cons in last name even?
names['LCdummy'] = names['lastCons'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the total number of vowels in name even?
names['TVdummy'] = names['totalVowels'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the total number of cons in name even?
names['TCdummy'] = names['totalCons'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the ratio of length of full name to number of vowels even?
names['FtVdummy'] = names['FtVratio'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the ratio of length of full name to number of consonants even?
names['FtCdummy'] = names['FtCratio'].apply(lambda x: 1 if x%2 == 0 else 0)

# Is the ratio of consonants to number of vowels even?
names['CtVdummy'] = names['FtCratio'].apply(lambda x: 1 if x%2 == 0 else 0)

In [107]:
names['total_length'] = (names['totalVowels']+names['totalCons']) # total length of name

In [110]:
names['Vowel_Fdummy'] = names['first name'].apply(lambda x: 1 if x[0] in vowels else 0) # Is first letter in name a vowel?

names['Vowel_Sdummy'] = names['first name'].apply(lambda x: 1 if x[1] in vowels else 0) # Is second a letter in name a vowel?

# As you can see, I threw in everything including the kitchen sink 

I ended up with 33 unique predictor variables

In [111]:
names.head(5)

first name middle name last name label  length of first  length of last  \
0      Naoki                   Abe     +                5               3   
1     Myriam              Abramson     -                6               8   
2      David          W.       Aha     +                5               3   
3      Kamal          M.       Ali     +                5               3   
4       Eric              Allender     -                4               8   

   firstvowels  firstCons  lastvowels  lastCons  ...  LVdummy  LCdummy  \
0            3          2           2         1  ...        1        0   
1            2          4           3         5  ...        0        0   
2            2          3           2         1  ...        1        0   
3            2          3           2         1  ...        1        0   
4            2          2           3         5  ...        0        0   

   TVdummy  TCdummy  FtVdummy  FtCdummy  CtVdummy  total_length  Vowel_Fdummy  \
0        0        0         1         0         0             8             0   
1        0        0         0         1         1            14             0   
2        1        1         1         1         1            10             0   
3        1        1         1         1         1            10             0   
4        0        0         1         1         1            12             1   

   Vowel_Sdummy  
0             1  
1             0  
2             1  
3             1  
4             0  

[5 rows x 34 columns]

In [112]:
names.columns

Index(['first name', 'middle name', 'last name', 'label', 'length of first',
       'length of last', 'firstvowels', 'firstCons', 'lastvowels', 'lastCons',
       'middledummy', 'totalVowels', 'totalCons', 'VtFratio', 'CtFratio',
       'VtCratio', 'FtVratio', 'FtCratio', 'CtVratio', 'tot_lengthdummy',
       'LoFdummy', 'LoLdummy', 'FVdummy', 'FCdummy', 'LVdummy', 'LCdummy',
       'TVdummy', 'TCdummy', 'FtVdummy', 'FtCdummy', 'CtVdummy',
       'total_length', 'Vowel_Fdummy', 'Vowel_Sdummy'],
      dtype='object')

In [116]:
names1 = names[['total_length', 'middledummy', 'tot_lengthdummy',
       'Vowel_Fdummy', 'Vowel_Sdummy', 'LoFdummy', 'LoLdummy', 'FVdummy', 'FCdummy', 'LVdummy', 'LCdummy',
       'TVdummy', 'TCdummy', 'FtVdummy', 'FtCdummy', 'CtVdummy', 'label']]

# I ultimately selected the 16 above to work with, prioritizing the dummy variables. The machine will easily learn with that.

In [117]:
names1.head()

total_length  middledummy  tot_lengthdummy  Vowel_Fdummy  Vowel_Sdummy  \
0             8            0                1             0             1   
1            14            0                1             0             0   
2            10            1                1             0             1   
3            10            1                1             0             1   
4            12            0                1             1             0   

   LoFdummy  LoLdummy  FVdummy  FCdummy  LVdummy  LCdummy  TVdummy  TCdummy  \
0         0         0        0        1        1        0        0        0   
1         1         1        1        1        0        0        0        0   
2         0         0        1        0        1        0        1        1   
3         0         0        1        0        1        0        1        1   
4         1         1        1        1        0        0        0        0   

   FtVdummy  FtCdummy  CtVdummy label  
0         1         0         0     +  
1         0         1         1     -  
2         1         1         1     +  
3         1         1         1     +  
4         1         1         1     -

In [70]:
names['label'].value_counts()

+    210
-     84
Name: label, dtype: int64

In [118]:
names1['label'].value_counts()

+    210
-     84
Name: label, dtype: int64

In [72]:
names.columns

Index(['first name', 'middle name', 'last name', 'label', 'length of first',
       'length of last', 'firstvowels', 'firstCons', 'lastvowels', 'lastCons',
       'middledummy', 'totalVowels', 'totalCons', 'VtFratio', 'CtFratio',
       'VtCratio'],
      dtype='object')

In [78]:
from sklearn.model_selection import train_test_split

In [119]:
X = names1.drop('label', axis=1)

In [120]:
y = names1['label']

In [121]:
X.head()

total_length  middledummy  tot_lengthdummy  Vowel_Fdummy  Vowel_Sdummy  \
0             8            0                1             0             1   
1            14            0                1             0             0   
2            10            1                1             0             1   
3            10            1                1             0             1   
4            12            0                1             1             0   

   LoFdummy  LoLdummy  FVdummy  FCdummy  LVdummy  LCdummy  TVdummy  TCdummy  \
0         0         0        0        1        1        0        0        0   
1         1         1        1        1        0        0        0        0   
2         0         0        1        0        1        0        1        1   
3         0         0        1        0        1        0        1        1   
4         1         1        1        1        0        0        0        0   

   FtVdummy  FtCdummy  CtVdummy  
0         1         0         0  
1         0         1         1  
2         1         1         1  
3         1         1         1  
4         1         1         1

# As we will see, a single tree worked great, with 100% accuracy. I didn't need  a whole forest :)

Nevertheless, I have another model below with the forest.

One might rightly wonder if all these variables were useful, I went all in at first. Now that I realize my model is working great, I decided to find the best variables. You will see the results further down.

I used the RFE from sklearn.feature_selection to select the top six variables:

1. What is the total length of the person's name? ('total_length') 

2. Is the first letter of the person's name a vowel? ('Vowel_Fdummy') 

3. Is the second letter of the name a vowel? ('Vowel_Sdummy') 

4. Is the length of last name an even number? ('LoLdummy') 

5. Is the number of vowels in first name an even numer? ('FVdummy')

6. Is there a middle name? ('middledummy')

In [122]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [123]:
from sklearn.tree import DecisionTreeClassifier

In [124]:
dtree = DecisionTreeClassifier()

In [125]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [126]:
predictions = dtree.predict(X_test)

In [127]:
y_test

27     +
283    -
201    +
118    -
293    +
129    +
28     +
158    +
218    +
52     -
289    +
103    +
243    +
135    +
178    -
205    +
108    +
5      +
266    +
146    -
284    -
251    +
45     +
236    +
104    +
123    -
83     +
210    -
234    -
112    +
      ..
259    +
200    -
56     -
142    +
145    +
11     +
282    -
99     +
34     +
86     +
275    +
232    +
12     +
195    +
267    +
241    +
126    +
172    +
127    +
265    +
288    +
4      -
124    +
19     +
80     -
254    +
263    +
2      +
264    -
90     +
Name: label, Length: 89, dtype: object

In [128]:
predictions

array(['+', '-', '+', '-', '+', '+', '+', '+', '+', '-', '+', '+', '+',
       '+', '-', '+', '+', '+', '+', '-', '-', '+', '+', '+', '+', '-',
       '+', '-', '-', '+', '+', '+', '+', '-', '-', '+', '-', '+', '+',
       '-', '-', '-', '-', '+', '+', '+', '+', '-', '+', '+', '-', '+',
       '+', '+', '+', '-', '-', '-', '+', '+', '-', '-', '+', '+', '+',
       '-', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '-', '+', '+', '-', '+', '+', '+', '-', '+'],
      dtype=object)

In [129]:
from sklearn.metrics import classification_report, confusion_matrix

In [130]:
print(classification_report(y_test,predictions))
print('\n')
print (confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           +       1.00      1.00      1.00        62
           -       1.00      1.00      1.00        27

   micro avg       1.00      1.00      1.00        89
   macro avg       1.00      1.00      1.00        89
weighted avg       1.00      1.00      1.00        89



[[62  0]
 [ 0 27]]


In [131]:
from sklearn.ensemble import RandomForestClassifier

In [132]:
rfc = RandomForestClassifier(n_estimators=1000)

In [133]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [134]:
rfc_pred = rfc.predict(X_test)

In [135]:
rfc_pred

array(['+', '-', '+', '-', '+', '+', '+', '+', '+', '-', '+', '+', '+',
       '+', '-', '+', '+', '+', '+', '-', '-', '+', '+', '+', '+', '-',
       '+', '-', '-', '+', '+', '+', '+', '-', '-', '+', '-', '+', '+',
       '-', '-', '-', '-', '+', '+', '+', '+', '-', '+', '+', '-', '+',
       '+', '+', '+', '-', '-', '-', '+', '+', '-', '-', '+', '+', '+',
       '-', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+',
       '+', '+', '-', '+', '+', '-', '+', '+', '+', '-', '+'],
      dtype=object)

In [136]:
y_test

27     +
283    -
201    +
118    -
293    +
129    +
28     +
158    +
218    +
52     -
289    +
103    +
243    +
135    +
178    -
205    +
108    +
5      +
266    +
146    -
284    -
251    +
45     +
236    +
104    +
123    -
83     +
210    -
234    -
112    +
      ..
259    +
200    -
56     -
142    +
145    +
11     +
282    -
99     +
34     +
86     +
275    +
232    +
12     +
195    +
267    +
241    +
126    +
172    +
127    +
265    +
288    +
4      -
124    +
19     +
80     -
254    +
263    +
2      +
264    -
90     +
Name: label, Length: 89, dtype: object

In [137]:
print(classification_report(y_test,rfc_pred))
print('\n')
print (confusion_matrix(y_test,rfc_pred))

              precision    recall  f1-score   support

           +       1.00      1.00      1.00        62
           -       1.00      1.00      1.00        27

   micro avg       1.00      1.00      1.00        89
   macro avg       1.00      1.00      1.00        89
weighted avg       1.00      1.00      1.00        89



[[62  0]
 [ 0 27]]


In [138]:
from sklearn.feature_selection import RFE

In [139]:
rfe = RFE(rfc, 5)

In [140]:
fit = rfe.fit(X_train, y_train)

In [141]:
fit.n_features_

5

In [143]:
fit.support_

array([ True, False, False,  True,  True, False,  True,  True, False,
       False, False, False, False, False, False, False])

In [144]:
fit.ranking_

array([ 1,  2,  4,  1,  1,  8,  1,  1,  9,  3, 10,  6, 12,  7,  5, 11])

In [147]:
X_train.columns

Index(['total_length', 'middledummy', 'tot_lengthdummy', 'Vowel_Fdummy',
       'Vowel_Sdummy', 'LoFdummy', 'LoLdummy', 'FVdummy', 'FCdummy', 'LVdummy',
       'LCdummy', 'TVdummy', 'TCdummy', 'FtVdummy', 'FtCdummy', 'CtVdummy'],
      dtype='object')

In [149]:
X = names1[['total_length', 'Vowel_Fdummy',  'Vowel_Sdummy', 'LoLdummy', 'FVdummy', 'middledummy']]

In [151]:
y = names1['label']

In [152]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [153]:
rfc = RandomForestClassifier(n_estimators=1000)

In [154]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [155]:
rfc_pred = rfc.predict(X_test)

In [156]:
rfc_pred

array(['+', '+', '-', '+', '-', '+', '+', '+', '+', '+', '+', '+', '+',
       '-', '+', '+', '+', '+', '+', '+', '-', '+', '+', '+', '+', '-',
       '-', '+', '+', '+', '-', '+', '+', '+', '+', '+', '+', '+', '-',
       '-', '+', '+', '+', '-', '+', '+', '+', '-', '-', '+', '-', '-',
       '-', '+', '+', '+', '+', '-', '+', '+', '+', '-', '-', '+', '+',
       '-', '+', '+', '+', '+', '+', '+', '+', '+', '-', '-', '+', '-',
       '+', '+', '+', '+', '+', '-', '+', '+', '+', '+', '+'],
      dtype=object)

In [157]:
print(classification_report(y_test,rfc_pred))
print('\n')
print (confusion_matrix(y_test,rfc_pred))

              precision    recall  f1-score   support

           +       1.00      1.00      1.00        66
           -       1.00      1.00      1.00        23

   micro avg       1.00      1.00      1.00        89
   macro avg       1.00      1.00      1.00        89
weighted avg       1.00      1.00      1.00        89



[[66  0]
 [ 0 23]]


In [158]:
rfc1 = RandomForestClassifier(n_estimators=20)

In [159]:
rfc1.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [160]:
rfc1_pred = rfc1.predict(X_test)

In [161]:
rfc1_pred

array(['+', '+', '-', '+', '-', '+', '+', '+', '+', '+', '+', '+', '+',
       '-', '+', '+', '+', '+', '+', '+', '-', '+', '+', '+', '+', '-',
       '-', '+', '+', '+', '-', '+', '+', '+', '+', '+', '+', '+', '-',
       '-', '+', '+', '+', '-', '+', '+', '+', '-', '-', '+', '-', '-',
       '-', '+', '+', '+', '+', '-', '+', '+', '+', '-', '-', '+', '+',
       '-', '+', '+', '+', '+', '+', '+', '+', '+', '-', '-', '+', '-',
       '+', '+', '+', '+', '+', '-', '+', '+', '+', '+', '+'],
      dtype=object)

In [162]:
print(classification_report(y_test,rfc1_pred))
print('\n')
print (confusion_matrix(y_test,rfc1_pred))

              precision    recall  f1-score   support

           +       1.00      1.00      1.00        66
           -       1.00      1.00      1.00        23

   micro avg       1.00      1.00      1.00        89
   macro avg       1.00      1.00      1.00        89
weighted avg       1.00      1.00      1.00        89



[[66  0]
 [ 0 23]]
